# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "RDKit MCP Server Eval"

prompts:
  - "What is the molecular weight of {{smiles}}?"

providers:
  - id: 'file://python_provider.py'
    label: 'Python agent'

tests:
  - vars:
      smiles: "CC(=O)NC1=CC=C(C=C1)O"
    description: "Verify molecular weight of `CC(=O)NC1=CC=C(C=C1)O` is approximately 180"
    assert:
      - type: llm-rubric
        value: "The final output states the Molecular weight is 151.165"
      - type: llm-rubric
        value: "The 'tool_calls' contains a call to `mol_wt` with the exact smiles `CC(=O)NC1=CC=C(C=C1)O` as an argument"
