# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "RDKit MCP Server Eval"

prompts:
  - "What is the molecular weight of {{smiles}}?"

providers:
  - id: 'file://python_provider.py'
    label: 'Python agent'

tests:
  - vars:
      smiles: "CC(=O)NC1=CC=C(C=C1)O"
      mol_weight: 151.165
    description: "Verify molecular weight of `CC(=O)NC1=CC=C(C=C1)O`"
    assert:
      - type: llm-rubric
        value: "The final output states the Molecular weight is {{mol_weight}} g/mol."
      - type: llm-rubric
        value: "The 'function_calls' key contains a call to `mol_wt` with the exact smiles `{{smiles}}` as an argument."
      - type: llm-rubric
        value: "The 'function_calls' key contains a function_call_output type which returns the value {{mol_weight}} g/mol."
